create extension if not exists pgcrypto;

create table if not exists public.rt_users (
  username text primary key,
  password text not null,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.rt_user_profiles (
  username text primary key,
  display_name text not null,
  avatar_url text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.rt_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  content text not null,
  image_url text,
  "to" text,
  reply_to bigint,
  reply_preview jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.rt_online_users (
  name text primary key,
  last_seen timestamptz not null default now(),
  typing boolean not null default false,
  typing_room text,
  last_typing timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.rt_private_channels (
  id bigint generated by default as identity primary key,
  room text not null unique,
  user1 text not null,
  user2 text not null,
  last_activity timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint rt_private_channels_room_check check (char_length(room) between 3 and 32)
);

create table if not exists public.rt_private_messages (
  id bigint generated by default as identity primary key,
  channel_id bigint not null references public.rt_private_channels(id) on delete cascade,
  sender text not null,
  message text not null,
  image_url text,
  reply_to bigint,
  reply_preview jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_rt_messages_created_at on public.rt_messages(created_at asc);
create index if not exists idx_rt_messages_to on public.rt_messages("to");
create index if not exists idx_rt_online_users_last_seen on public.rt_online_users(last_seen desc);
create index if not exists idx_rt_private_channels_users on public.rt_private_channels(user1, user2);
create index if not exists idx_rt_private_messages_channel_id on public.rt_private_messages(channel_id);
create index if not exists idx_rt_private_messages_created_at on public.rt_private_messages(created_at asc);

alter table public.rt_messages replica identity full;
alter table public.rt_online_users replica identity full;
alter table public.rt_private_channels replica identity full;
alter table public.rt_private_messages replica identity full;
alter table public.rt_user_profiles replica identity full;

alter table public.rt_messages enable row level security;
alter table public.rt_online_users enable row level security;
alter table public.rt_private_channels enable row level security;
alter table public.rt_private_messages enable row level security;
alter table public.rt_user_profiles enable row level security;

-- Realtime do navegador usa a anon key, então precisa de SELECT liberado para o teste.
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='rt_messages' and policyname='rt_messages_select_all'
  ) then
    create policy rt_messages_select_all on public.rt_messages for select to anon, authenticated using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='rt_online_users' and policyname='rt_online_users_select_all'
  ) then
    create policy rt_online_users_select_all on public.rt_online_users for select to anon, authenticated using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='rt_private_channels' and policyname='rt_private_channels_select_all'
  ) then
    create policy rt_private_channels_select_all on public.rt_private_channels for select to anon, authenticated using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='rt_private_messages' and policyname='rt_private_messages_select_all'
  ) then
    create policy rt_private_messages_select_all on public.rt_private_messages for select to anon, authenticated using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='rt_user_profiles' and policyname='rt_user_profiles_select_all'
  ) then
    create policy rt_user_profiles_select_all on public.rt_user_profiles for select to anon, authenticated using (true);
  end if;
end $$;

-- Coloca as tabelas de teste no Realtime.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rt_messages'
  ) then
    alter publication supabase_realtime add table public.rt_messages;
  end if;

  if not exists (
    select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rt_online_users'
  ) then
    alter publication supabase_realtime add table public.rt_online_users;
  end if;

  if not exists (
    select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rt_private_channels'
  ) then
    alter publication supabase_realtime add table public.rt_private_channels;
  end if;

  if not exists (
    select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rt_private_messages'
  ) then
    alter publication supabase_realtime add table public.rt_private_messages;
  end if;

  if not exists (
    select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rt_user_profiles'
  ) then
    alter publication supabase_realtime add table public.rt_user_profiles;
  end if;
end $$;

-- Usuário inicial de teste. Troque depois se quiser.
insert into public.rt_users (username, password, is_admin)
values ('admin', 'admin123', true)
on conflict (username) do nothing;

insert into public.rt_user_profiles (username, display_name, avatar_url)
values ('admin', 'admin', null)
on conflict (username) do nothing;
